name: Deploy to gh-pages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
      uses: actions/setup-python@v2
      - name: Restore mtime
      run: python ./git-restore-mtime.py
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - run: npm install
      - run: npm run build

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: trunk build --release --public-url valentine2022

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
